- id: set_lzw45_pixel_effect
  alias: Set LZW45 Pixel Effect on Input Select Change
  trigger:
    platform: state
    entity_id: input_select.laundry_strip_pixel_effect
  action:
    service: script.lzw45_pixel_effect
    data:
      lzw45: light.laundry_room_light_strip

- id: toggle_living_room
  alias: Toggle Living Room Lights on Inovelli press
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 9
      label: Scene 002
      value: KeyPressed
  action:
    service: light.toggle
    entity_id: light.living_room_lights

- id: event_update_wakeup_time
  alias: Update wakeup time when event triggered (for updating via Google Assistant).
  trigger:
    platform: event
    event_type: update_wakeup_time
  action:
  - service: input_datetime.set_datetime
    data:
      entity_id: input_datetime.wakeup_time
      time: '{{ trigger.event.data.wakeup_time }}'
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.wakeup_enabled
  - condition: time
    weekday:
    - fri
    - sat
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.wakeup_weekend
- id: alarm_notification
  alias: Notify me when intrusion detected.
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_occupancy
    to: 'on'
  condition:
    - condition: state
      entity_id: person.me
      state:  'away'
  action:
  - service: notify.mobile_app_cphone
    data:
      title: 'Motion Detected'
      message: 'Motion Detected at Home.'
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0
