- platform: mqtt
  name: ozw_network_ready
  state_topic: OpenZWave/1/status/
  value_template: >
    {{ "ON" if value_json.Status in ["driverAwakeNodesQueried", "driverAllNodesQueriedSomeDead", "driverAllNodesQueried"] else "OFF" }}
  json_attributes_topic: OpenZWave/1/status/
  device_class: "connectivity"
- platform: template
  sensors:
    front_door_motion:
      friendly_name: "Front Door Motion"
      device_class: motion
      value_template: "{{ is_state('input_boolean.front_door_motion', 'on') }}"
