- platform: group
  name: Fan Light
  entities:
    - light.fan_bulb_1
    - light.fan_bulb_2
    - light.fan_bulb_3

- platform: group
  name: Living Room East Lights
  entities:
    - light.couch_light
    - light.wall_bulb_west
    - light.wall_bulb_east

- platform: group
  name: Wall Lights
  entities:
    - light.wall_bulb_west
    - light.wall_bulb_east
    

- platform: group
  name: Living Room Lights
  entities:
    - light.fan_light
    - light.living_room_east_lights

- platform: group
  name: Laundry Room Lights
  entities:
    - light.laundry_room_light
    - light.laundry_room_light_strip

- platform: group
  name: West Lights
  entities:
    - light.laundry_room_lights
    - light.kitchen_light

- platform: group
  name: Non Kitchen Main Lights
  entities:
    - light.living_room_lights
    - light.laundry_room_lights

- platform: group
  name: Main Lights
  entities:
    - light.living_room_lights
    - light.west_lights

- platform: group
  name: Indoor Lights
  entities:
    - light.living_room_lights
    - light.bedroom_light
    - light.kitchen_light
    - light.laundry_room_lights
