- platform: time_date
  display_options:
    - 'time'
- platform: systemmonitor
  resources:
    - type: processor_temperature
    - type: memory_use_percent
    - type: disk_use_percent
    - type: processor_use
